Updates for latest versions to ensure can run on latesrt stacks etc

diff --git a/api/Dockerfile b/api/Dockerfile
--- a/api/Dockerfile
+++ b/api/Dockerfile
@@ -4,8 +4,8 @@
 
 # https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
 ARG PHP_VERSION=7.4
-ARG OPENRESTY_VERSION=1.15.8.3
-ARG VARNISH_VERSION=6.4
+ARG OPENRESTY_VERSION=1.21.4.1-0
+ARG VARNISH_VERSION=7.1
 
 # "php" stage
 FROM registry.gitlab.com/silverback-web-apps/cwa/docker/php:${PHP_VERSION}-fpm-alpine AS cwa_php
@@ -17,7 +17,8 @@ COPY _docker/php/conf.d $PHP_INI_DIR/
 ENV COMPOSER_ALLOW_SUPERUSER=1
 # install Symfony Flex globally to speed up download of Composer packages (parallelized prefetching)
 RUN set -eux; \
-	composer global require "symfony/flex" --prefer-dist --no-progress --no-suggest --classmap-authoritative; \
+	composer global config --no-plugins allow-plugins.symfony/flex true; \
+    composer global require "symfony/flex" --prefer-dist --no-progress --no-suggest --classmap-authoritative; \
 	composer clear-cache
 ENV PATH="${PATH}:/root/.composer/vendor/bin"
 
@@ -69,21 +70,40 @@ WORKDIR /srv/api/public
 
 COPY --from=cwa_php /srv/api/public ./
 
-
 # "varnish" stage
-# does not depend on any of the above stages, but placed here to keep everything in one Dockerfile
+# does not depend on any of the above stages
 FROM varnish:${VARNISH_VERSION} AS cwa_varnish
 
-RUN \
-  apt-get update \
-  && apt-get -y install gettext-base \
-  && apt-get clean \
-  && rm -rf /var/lib/apt/lists/*
+#USER root
+#
+#RUN set -e; \
+#    apt-get update; \
+#    apt-get -y install gettext-base $VMOD_DEPS /pkgs/*.deb; \
+#    \
+## install one, possibly multiple vmods
+#   install-vmod https://github.com/varnish/varnish-modules/releases/download/0.20.0/varnish-modules-0.20.0.tar.gz; \
+#    \
+## clean up and set the user back to varnish
+#    apt-get -y purge --auto-remove $VMOD_DEPS varnish-dev; \
+#    rm -rf /var/lib/apt/lists/*
+#
+#USER varnish
 
-COPY _docker/varnish/conf/default.vcl /tmp/varnish/conf/default.vcl
+USER root
+RUN apt-get update; apt-get -y install gettext-base
+
+#COPY _docker/varnish/conf/default.vcl /tmp/varnish/conf/default.vcl
+#CMD ["envsubst", "'${UPSTREAM},${UPSTREAM_PORT},${PHP_SERVICE},${CORS_ALLOW_ORIGIN}' < /tmp/varnish/conf/default.vcl > /etc/varnish/default.vcl"]
+
 COPY _docker/varnish/persist-environment.sh /usr/local/bin/persist-environment
+COPY _docker/varnish/conf/default.vcl /tmp/varnish/conf/default.vcl
 
-RUN chmod +x /usr/local/bin/persist-environment
-ENTRYPOINT ["persist-environment", "docker-varnish-entrypoint"]
+RUN chmod -R 777 /tmp/varnish/conf \
+    && chmod -R 777 /etc/varnish \
+    && chmod +x /usr/local/bin/persist-environment
 
-CMD ["varnishd", "-F", "-f", "/etc/varnish/default.vcl", "-p", "http_resp_hdr_len=65536", "-p", "http_resp_size=98304", "-p", "workspace_backend=512K"]
+USER varnish
+
+EXPOSE 8080
+ENTRYPOINT ["/usr/local/bin/docker-varnish-entrypoint", "/usr/local/bin/persist-environment"]
+CMD ["varnishd", "-F", "-f", "/etc/varnish/default.vcl", "-p", "http_resp_hdr_len=65536", "-p", "http_resp_size=98304", "-p", "workspace_backend=512K", "-a", "http=:8080,HTTP", "-a", "proxy=:8443,PROXY", "-p", "feature=+http2", "-s", "malloc,100M"]
